/**
 * \file IfxSmu_PinMap_TC37x_LQFP176.h
 * \brief SMU I/O map
 * \ingroup IfxLld_Smu
 *
 * \version iLLD_1_22_0
 * \copyright Copyright (c) 2026 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Infineon Technologies AG (Infineon) licenses this file to you under the
 * Infineon Automotive SW Lab License v2025-01 (IFASLL). You may not use
 * this file except in compliance with IFASLL.
 *
 * The full license text is contained in IFASLL202501.pdf delivered with this SW.
 * Unless required by applicable law or agreed to in writing, software distributed
 * under this license is distributed "AS IS" without any warranty or liability of any
 * kind and Infineon hereby expressly disclaims any warranties or representations,
 * whether express, implied, statutory or otherwise, including but not limited to
 * warranties of workmanship, merchantability, fitness for a particular purpose,
 * defects in the licensed items, or non-infringement of third parties'
 * intellectual property rights. See the full license text for the specific
 * language governing permissions and limitations under IFASLL.
 *
 * \defgroup IfxLld_Smu_pinmap SMU Pin Mapping
 * \ingroup IfxLld_Smu
 */

#ifndef IFXSMU_PINMAP_TC37X_LQFP176_H
#define IFXSMU_PINMAP_TC37X_LQFP176_H 1

#include <IfxSmu_reg.h>
#include <Port/Std/IfxPort.h>
#include "Ifx_PinMap.h"

/** \addtogroup IfxLld_Smu_pinmap
 * \{ */

/** \brief Fault Signal Protocol Pin */
typedef const struct
{
    Ifx_SMU*          module;    /**< \brief Base address */
    IfxPort_Pin       pin;       /**< \brief Port pin */
    IfxPort_OutputIdx select;    /**< \brief Port control code */
} IfxSmu_Fsp_Out;

IFX_EXTERN IfxSmu_Fsp_Out IfxSmu_FSP0_P33_8_OUT;  /**< \brief FSP[1..0] Output Signals - Generated by SMU_core */
IFX_EXTERN IfxSmu_Fsp_Out IfxSmu_FSP1_P33_10_OUT;  /**< \brief FSP[1..0] Output Signals - Generated by SMU_core */

/** \brief Table dimensions */
#define IFXSMU_PINMAP_NUM_MODULES 1
#define IFXSMU_PINMAP_FSP_OUT_NUM_ITEMS 2


/** \brief IfxSmu_Fsp_Out table */
IFX_EXTERN const IfxSmu_Fsp_Out *IfxSmu_Fsp_Out_pinTable[IFXSMU_PINMAP_NUM_MODULES][IFXSMU_PINMAP_FSP_OUT_NUM_ITEMS];

/** \} */

#endif /* IFXSMU_PINMAP_TC37X_LQFP176_H */
